### ISSUE TITLE
Unmatch ImageViewerCaptureTool() constructor

### ISSUE THREAD

**Issue by Thomio-Watanabe** [Brazilian-Institute-of-Robotics/simulation-orogen-imaging_sonar_simulation#9]
It seems this package needs a **ImageViewerCaptureTool()** constructor with 4 arguments. 
ImageViewerCaptureTool() is defined in gui-vizkit3d_normal_depth_map package.
https://github.com/Brazilian-Institute-of-Robotics/gui-vizkit3d_normal_depth_map

**Comment by romulogcerqueira** [comment]
Hi @Thomio-Watanabe ,

I updated the branch set_near_far_and_culling_mode on vizkit3d_normal_depth_map. Please check it again.

**Comment by Thomio-Watanabe** [comment]
Solved !
